### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by i1d9** [hatamiarash7/LL1_Parser#1]
Default string from the repo gives index error yet it is inthe grammar

**Comment by hatamiarash7** [comment]
I did not understand what you meant. That's a python error or you mean that the algorithm has a problem?

**Comment by i1d9** [comment]
![image](https://user-images.githubusercontent.com/42600121/112596332-bad9da80-8e1c-11eb-9757-498bb1abed5f.png)

When i run the code without modification it raises the IndexError using the string "aabd" as shown here-> parse("aabd", start, ll1Table)

**Comment by hatamiarash7** [comment]
Can you share the full error? There isn't any problem with the code. What version of Python are you using and have you installed [Pandas](https://pandas.pydata.org/)?

**Comment by i1d9** [comment]
Here's the error on the terminal. I just cloned the repo and tried to run the code

![image](https://user-images.githubusercontent.com/42600121/112598949-528cf800-8e20-11eb-8c76-478c784ef748.png)

Am using python 3.9 and I have installed pandas.

**Comment by hatamiarash7** [comment]
Did you find the problem?
